config/routes.rb
Rtf::Application.routes.draw do
  
  resources :repos
  
  

end

app/models/repo.rb
require 'fileutils'
require 'io'
require 'open3'

class Repo < ActiveRecord::Base
  include Io
  
  def git_create
    g = repo rescue Git.clone(repo_path, git_path)
    g.checkout('master')
  end
  
  def git_update
    r = repo
    r.pull
    # Commit.find_or_create r.gcommit('HEAD')
  end
  
  def recalculate
    git_update
    parse_output *run_commands
  end
  
  def git_cleanup
    FileUtils.rm_rf git_path if File.exists? git_path
  end
  
private
  def repo
    # throws ArgumentError if the repo doesn't exist
    Git.open git_path, :log => logger
    # g = Git.clone(URI, :name => 'name', :path => '/tmp/checkout')  
  end
  
  def git_path
    File.join('repositories',id.to_s)
  end
  
  def run_commands
    commands = setup_command.split("\n")
    commands.push cucumber_comand
    
    orig_ENV = ENV.to_hash
    ENV.clear
    capture do
      stdin, stdout, stderr, thread  = Open3.popen3(commands.join(';'))
      stdin.close
      $stdout.print stdout.read
      $stderr.print stderr.read
      stdout.close
      stderr.close
      thread.value.exitstatus
    end
  ensure
    ENV.clear
    orig_ENV.to_hash.each{ |k, v| ENV[k] = v}
  end
  
  def parse_output(status,output,error)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  # GET /repos
  # GET /repos.xml
  def index
    @repos = Repo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @repos }
    end
  end

  # GET /repos/1
  # GET /repos/1.xml
  def show
    @repo = Repo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @repo }
    end
  end

  # GET /repos/new
  # GET /repos/new.xml
  def new
    @repo = Repo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @repo }
    end
  end

  # GET /repos/1/edit
  def edit
    @repo = Repo.find(params[:id])
  end

  # POST /repos
  # POST /repos.xml
  def create
    @repo = Repo.new(params[:repo])

    respond_to do |format|
      if @repo.save
        format.html { redirect_to(@repo, :notice => 'Repo was successfully created.') }
        format.xml  { render :xml => @repo, :status => :created, :location => @repo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @repo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /repos/1
  # PUT /repos/1.xml
  def update
    @repo = Repo.find(params[:id])

    respond_to do |format|
      if @repo.update_attributes(params[:repo])
        format.html { redirect_to(@repo, :notice => 'Repo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @repo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.xml
  def destroy
    @repo = Repo.find(params[:id])
    @repo.destroy

    respond_to do |format|
      format.html { redirect_to(repos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rtf</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/repos/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :repo_path %><br />
    <%= f.text_field :repo_path %>
  </div>
  <div class="field">
    <%= f.label :setup_command %><br />
    <%= f.text_area :setup_command %>
  </div>
  <div class="field">
    <%= f.label :cucumber_comand %><br />
    <%= f.text_area :cucumber_comand %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repos/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<h1>Listing repos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repos.each do |repo| %>
  <tr>
    <td><%= repo.name %></td>
    <td><%= repo.repo_path %></td>
    <td><%= link_to 'Show', repo %></td>
    <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
    <td><%= link_to 'Destroy', repo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repo', new_repo_path %>

app/views/repos/new.html.erb
<h1>New repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repos/show.html.erb
<h1><%= @repo.name %></h1>
<p id="notice"><%= notice %></p>

<%= @repo.repo_path %>
<pre>
  <%= @repo.setup_command %>
</pre>
<pre>
  <%= @repo.cucumber_comand %>
</pre>
<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>